name: CI

on:
  push:
    branches: [ "main" ]
    # Skip CI jobs for commits that contain [ci skip] in the message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
  # Schedule the workflow to run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip CI jobs for commits that contain [ci skip] in the message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Compile host list
        id: compile
        uses: Satellite-Galaxy/HostListCompiler-Action@latest
        with:
          config: compiler.json
          output: hosts.txt
      - name: Push compiled hosts file to main branch
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update compiled host list"
          add: "hosts.txt"
          branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
