name: CI

on:
  push:
    branches: [ "main" ]
    # Skip CI jobs for commits that contain [ci skip] in the message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
  # Schedule the workflow to run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip CI jobs for commits that contain [ci skip] in the message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}
      - name: Compile host list
        id: compile
        uses: Satellite-Galaxy/HostListCompiler-Action@latest
        with:
          config: compiler.json
          output: hosts.txt
      - name: Commit and push compiled hosts file to main branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add hosts.txt
          git commit -m "Update compiled host list"
          git push
